# Generated by Django 2.2.10 on 2022-12-26 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_profilepro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fac', models.DateField()),
                ('ref_fac', models.CharField(max_length=50)),
                ('mnt_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mnt_regler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
